/*---------------------------------------------------------------------------
;
;
;
;
; 	FILE NAME  	: TP_Synthese_Lib_Config_Globale_8051F020.H
; 	TARGET MCUs	: C8051F020, 
; 	DESCRIPTION	: Configuration pour le TP BSE
;
; 	REVISION 1.0
;
;---------------------------------------------------------------------------*/

#ifndef __TP_Synthese_Lib_Config_Globale_8051F020__
#define __TP4_Synthese_Lib_Config_Globale_8051F020__


void Init_Device (void);
void Reset_Sources_Init(void);
void Port_IO_Init(void);
void Oscillator_Init_Osc_Quartz(void);
void Config_interrupt(void);
void Config_Timer(void);
void Config_UART0(void);

#endif